name: site

on: 
  workflow_dispatch: 
jobs:
  
  publish:
    runs-on: ubuntu-latest
    env:
      working-directory: examples
    strategy:
      matrix:
        node: ["14"]
    name: Node Version ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: poi
        working-directory: examples
        run: |
          npm install
          npm run build
      - uses: maxheld83/ghpages@v0.3.0
        name: GitHub Pages Deploy
        env:
          BUILD_DIR: "examples/dist/"
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: feishu-bot-message
        if: always()
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              ⭕️ gh-page 部署状态 - ${{ job.status }} 
              
              repository: https://github.com/${{ github.repository }}

              committer: https://github.com/${{ github.actor }}
              
              compare: ${{ github.event.compare }}

              online: https://unliar.github.io/typescript-react-hightlight-words/
