name: gh-page

on: [push]

jobs:
  
  publish:
    runs-on: ubuntu-latest
    env:
      working-directory: examples
    strategy:
      matrix:
        node: ["14"]
    name: Node Version ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install
        working-directory: examples
        run: |
          npm install
          npm run build
      - name: wechat-work-bot-success
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ✅ [typescipt-react-hightlight-words gh-page 发布成功](https://github.com/${{github.repository}}) \n
          "
      - name: wechat-work-bot-failed-build
        if: ${{ failure() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ❎ [typescipt-react-hightlight-words gh-page 发布失败](https://github.com/${{github.repository}}) \n
          " 