name: gh-page

on: 
  push:
    branches:
      - main
      - dev
jobs:
  
  publish:
    runs-on: ubuntu-latest
    env:
      working-directory: examples
    strategy:
      matrix:
        node: ["14"]
    name: Node Version ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: poi
        working-directory: examples
        run: |
          npm install
          npm run build
      - uses: maxheld83/ghpages@v0.3.0
        name: GitHub Pages Deploy
        env:
          BUILD_DIR: "dist/"
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: wechat-work-bot-success
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ✅ [typescipt-react-hightlight-words](https://github.com/${{github.repository}})  gh-page 发布成功 \n
          link: [click me](https://unliar.github.io/typescript-react-hightlight-words/)
          "
      - name: wechat-work-bot-failed-build
        if: ${{ failure() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ❎ [typescipt-react-hightlight-words](https://github.com/${{github.repository}})  gh-page 发布失败 \n
          link: [click me](https://unliar.github.io/typescript-react-hightlight-words/)
          " 