name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
    name: Node Version ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'get-previous-tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Generate site
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: site
          token: ${{ secrets.GH_PAT }}     
      - name: feishu-bot-message
        if: always()
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              ⭕️ npm publish 状态 - ${{ job.status }} 
              
              repository: https://github.com/${{ github.repository }}

              committer: https://github.com/${{ github.actor }}
              
              compare: ${{ github.event.compare }}

              desc: TAG=${{ steps.previoustag.outputs.tag }} 
